### ISSUE TITLE
engine: the boot/quit/relaunch smoke test stopped returning to the launcher, and regressed within a five-merge window

### ISSUE THREAD

**Issue by tylervick** [tylervick/waddle#184]
`WADdleUITests/EngineSmokeTests/testEngineBootQuitRelaunchCycle` fails on `main`: the engine session
starts but never returns to the launcher within its 90-second wait.

```
EngineSmokeTests.swift:31: error: XCTAssertTrue failed
    - cycle 1: engine did not return to launcher
```

Line 31 is `XCTAssertTrue(exitLabel.waitForExistence(timeout: 90), ...)`, waiting for
`engineExitLabel`. The preceding assertion — that any stale label from a previous cycle has cleared —
passes, so the session does start; it is the exit that never arrives, on the very first cycle.

**Reproducible, not a flake.** It failed on the `ui-tests.yml` run for the PR #178 merge and again on a
re-run of the same commit.

**It regressed within a known window.** The same test passed on the 2026-08-17T23:11Z run (the PR #172 /
#173 merges) and has failed on every run since. Merged in between:

| PR | Merged | Touches |
|---|---|---|
| #177 | 00:20 | `App/Sources/` — first-launch welcome card |
| #174 | 00:36 | `.github/workflows/ci.yml`, `mise.toml`, Scripts, a new unit test |
| #175 | 00:40 | `.github/workflows/{ci,issue-format,ui-tests}.yml` — dependency pinning |
| #176 | 00:40 | `App/project.yml` — ZIPFoundation to v0.9 |
| #178 | 01:31 | `App/Sources/` — detail page header art cap |

**What is already ruled out.** The welcome card (#177) is not involved: this test does **not** set
`WADDLE_RESET_STORE`, so it never sees factory state. That distinguishes it from the other current
failure, #183, which is entirely a factory-state layout problem.

**What is not ruled out, and is deliberately not asserted here.** #176 changed a package version and
#175 changed workflow pinning including `ui-tests.yml` itself. Either could plausibly matter — a
package bump changes what links into the app, and a workflow change alters the environment the engine
boots in. Neither has been tested against, and guessing between them is exactly what the investigation
below is for.

The engine itself is untouched: no merge in the window went near `Engine/`, `Scripts/build-engine.sh`,
or the vendored Woof pin.

## Definition of done

`EngineSmokeTests/testEngineBootQuitRelaunchCycle` passes on `main`, and the pull request states what
actually caused the regression — not merely what made the symptom go away.

The engine booting and exiting cleanly is the most load-bearing behaviour this app has; a fix that
suppresses the assertion, lengthens the timeout, or skips the test does not close this issue.

## Verification

Reproduce first, and locally before anything else:

```
mise run bootstrap
xcodebuild -project App/WADdle.xcodeproj -scheme WADdle \
  -destination 'platform=iOS Simulator,name=iPhone 17 Pro' \
  -only-testing:WADdleUITests/EngineSmokeTests test
```

If it passes locally and fails in CI, that is itself the finding — say so, and pursue the environment
difference rather than the app.

Bisect the window rather than reasoning about it. The five merges above are individually checkoutable;
running this one suite at each is the cheap, decisive experiment, and it names the cause instead of
inferring it.

Then confirm the fix by the same route it was found: the test must go from red to green on `main`,
which `ui-tests.yml` now reports on every merge.

## Provenance

Found 2026-08-17, on the second night `ui-tests.yml` ran automatically (PR #172, issue #170). Before
that change this suite had not run in 18 days across 84 merged pull requests, so a regression of this
shape would have gone unnoticed until someone dispatched the workflow by hand.

`docs/learnings/ui-tests-are-red-at-head.md` describes a *different*, now partly-resolved red state and
is being retired separately — do not take it as covering this one.

Agent-eligible, with one hard boundary: if the cause turns out to be the dependency version in
`App/project.yml` or anything in `mise.toml`, **stop and record `outcome: stuck`**. Changing a
dependency pin is forbidden by `Scripts/loop-prompt.md` → "Rules that are absolute", and identifying the
culprit is the valuable half of this work regardless of who applies the fix.

**Comment by tylervick** [comment]
**Reproducer found, measured 2026-08-18: it needs a *fresh app container*.** On a warm container the test passes; wipe the container and it fails every time, on `main`, with exactly the reported signature.

Isolated by holding one variable at a time on `iPhone 17 Pro`, simulator `A44DCE97-EEEC-4E37-A84C-BA535DC8CBB1`:

| Checkout | Container | Result |
|---|---|---|
| `main` | warm (state from earlier runs) | **TEST SUCCEEDED** (30s) |
| `main` | `simctl uninstall` first | **TEST FAILED** — `cycle 1: engine did not return to launcher` (line 31) |
| feature branch | `simctl uninstall` first | **TEST FAILED** — identical signature |

The warm run is not a fluke: it completed both cycles and the engine wrote its config (`Library/Application Support/woof/woof.cfg`, mtime matching the run). The wiped runs write **no config at all**, so `M_SaveDefaults` never ran — the engine is not exiting, which matches "the exit never arrives" in the issue body rather than a UI-only problem with the label.

**This explains the CI-versus-local split.** `ui-tests.yml` runs on a hosted runner where the simulator and app container are always clean, so it hits the failing path every time. Anyone running it locally against a simulator they have used before hits the passing path, which is why it can look unreproducible.

It also narrows the cause: something in the **first-launch** path is what the engine does not survive. A clean container means loose-file adoption of the bundled Freedoom WADs runs during that first launch (hashing and copying), concurrently with the session the test starts — `RealWADTests` already documents adoption being async off `ContentView`'s first `.task` and needing to be awaited separately. The warm path has nothing to adopt.

Suggested next step for whoever picks this up: re-run the wiped-container case with adoption forced to complete before the Play tap, and separately with `WADDLE_RESET_STORE` set on a warm container — that separates "first launch" from "empty library".

Found while verifying PR #198 (wavetable MIDI); that branch shows the same behaviour as `main`, so this is not related to it.

**Comment by tylervick** [comment]
Post-close evidence, for the record — this issue closed with PR #203, and the run history since bears that out while also explaining why the suite *looked* still-broken for two more days.

**The documented mode is extinct.** `testEngineBootQuitRelaunchCycle` across every full `ui-tests.yml` run since:

| Run | Merge | Date | EngineSmoke |
|---|---|---|---|
| 32391821515 | #206 | 08-20 | passed |
| 32395249827 | #205 | 08-20 | passed |
| 32395523105 | #185 | 08-20 | passed |
| 32524143146 | #208 | 08-21 | failed — different mode, below |
| 32535700151 | #209 | 08-21 | passed |

The 90-second `engineExitLabel` wait that defines this issue has not appeared once. The suite-level red on all five runs was `ShipUITests`' stale GPL-2.0 literal (broken by the 35a4561 relicense, fixed in PR #210) — which is why the suite stayed red after this issue's fix landed, and why the red kept being attributed here.

**On "the session does start."** That inference rested on the stale-label assertion, which on cycle 1 passes vacuously — there is no previous label to clear. So the evidence never distinguished "session started, exit lost" from "tap synthesized, never landed, no session at all." The second reading is #204's measured mechanism, and it is the one the fix history supports: red from 08-17, green from the first full run after the fold-clearance work merged.

**One new-mode occurrence, recorded as unreproduced** (one observation is not a backlog item). Run 32524143146, failing at 21s, not 90:

```
Failed to not hittable: Button, {{-84.3, 343.7}, {377.7, 236.0}},
identifier: 'playFreedoom1', label: 'Freedoom Phase 1'
```

377.7 × 236.0 is a 1.6:1 element — `Theme.heroAspectRatio`, i.e. the Continue hero, not a grid tile — sitting 84 pt off-screen left. It did not recur on the #209-merge run. If it recurs, file fresh with both data points and the xcresult UI-hierarchy attachments.

**Comment by tylervick** [comment]
Mechanism found for the one new-mode occurrence recorded above (run 32524143146, `Failed to not hittable: Button, {{-84.3, 343.7}, {377.7, 236.0}}, identifier: 'playFreedoom1'`).

`TitleArtView` rendered TITLEPIC with `scaledToFill`, and a filled image's oversized node leaks into the element's **accessibility frame** — `.clipped()` bounds drawing, never frames. At that run's geometry (pre-#199 3:4 tiles, two 177 pt columns), the tile's 320×200 art filled a 177×236 box at scale 1.18, giving an image node of 377.6 × 236 centred on the cell — origin x = 104.5 − 188.8 = **−84.3**. Every number in the flake's frame is that arithmetic; the button's reported frame was its bitmap's fill box, extending off-screen, which is what XCUITest's hittability check rejected. The same leak put a 210 pt accessibility frame on every 175 pt tile (measured 2026-08-21), so any element-frame-based interaction could flake this way at any geometry.

Fixed in the shelf design-pass branch: the fill crop moved into Core Graphics so SwiftUI never meets a bitmap wider than its box, and `PlayTabTests/testTilesStayInsideTheirGridCells` now measures the live hierarchy — it failed against the old rendering with exactly the collapsed-gap/negative-margin signature and passes after.
